#+Title: Unicode characters for LaTeX
#+Author: Mark Armstrong
#+Description: A collection of ~\NewUnicodeChar~ declarations for use in LaTeX.

#+begin_quote
See the associated [[http://armkeh.github.io/unicode-sty/index.html][webpage]] or [[https://armkeh.github.io/unicode-sty/unicode.pdf][PDF]] ^_^
#+end_quote

* Introduction

A collection of ~\newunicodechar~ declarations for use in LaTeX.

The file [[file:unicode.pdf][unicode.pdf]] is generated from [[file:unicode.org][unicode.org]] as
evidence that the unicode characters are declared correctly.

* Instruction on using this repository

There are at least three ways you could include of ~unicode.sty~ in
your project(s).
1. Copy ~unicode.sty~ and add it to your repo.
   - The disadvantage to this approach is that you must manually
     update ~unicode.sty~ if it changes here,
     and any changes you make to one local copy will not
     be carried over to other copies you make.
2. Clone this project or copy ~unicode.sty~, and place it
   —or a symlink to it— in a directory where LaTeX will find it.
   - The disadvantage to this approach is that it is machine local;
     users of your project on other machines must also perform
     the same setup.
3. Include this repository as a submodule of your repository,
   via, for instance, Git submodules or Git subtrees.
   - The disadvantage to this approach is you must learn
     how to use submodules if you do not already know how.

Option (3) seems the best option, and among Git's submodule mechanisms,
subtrees are apparently the best choice.
So this section describes how to include this repo as a subtree
of your project.

In the below, we add this repository under the directory ~unicode-sty~.
Change the prefix if you wish to place it elsewhere.
I do recommend making symbolic links to ~unicode-sty/unicode.sty~
throughout your project.

Adding the subtree is simple enough.
#+begin_src shell
git subtree add --prefix unicode-sty https://github.com/armkeh/unicode-sty.git master --squash
#+end_src
The ~--squash~ flag squashes the history of this repository;
if you prefer to include the full history of this project,
omit the flag.

To update the subtree when changes occur to this repository,
simply run
#+begin_src shell
git subtree pull --prefix unicode-sty https://github.com/armkeh/unicode-sty.git master --squash
#+end_src
Again, note the ~--squash~ flag.

To update the repository when changes occur to your subtree,
simply run
#+begin_src shell
git subtree push --prefix unicode-sty https://github.com/armkeh/unicode-sty.git master
#+end_src
Or replace ~https://github.com/armkeh/unicode-sty.git~ with the link
for your fork, if you wish to fork the project and then make a pull request.

* Instructions on using ~unicode.sty~

The below instructions are imported here from [[file:unicode.org][unicode.org]].
See that file for more details.

#+Include: "./unicode.org::*Usage"
#+Include: "./unicode.org::*Requirements"
#+Include: "./unicode.org::*Contributing to this document"

* .gitignore :noexport:

#+begin_src text :tangle .gitignore
# This file is tangled from a code in README.org.
# It should not be modified directly.
*~

*.aux
*.fdb_latexmk
*.fls
*.log
*.out
*.pyg
*.toc

# The LaTeX is generated; don't version control it.
*.tex

_minted-unicode
#+end_src
